### ISSUE TITLE
Configuration file support

### ISSUE THREAD

**Issue by chrisroberts** [miasma-rb/miasma-aws#15]
Now that the docs on the structure of these files has been expanded to provide all the details of their snowflakeiness, add support in to handle the insanity.

Reference doc: http://docs.aws.amazon.com/cli/latest/topic/config-vars.html
Required: http://docs.aws.amazon.com/cli/latest/topic/config-vars.html#service-specific-configuration

Also ensure that precedence is following along correctly as defined.

**Comment by dougireton** [comment]
Does SFN currently support ~/.aws/credentials and ~/.aws/config or only ENV vars right now?

**Comment by chrisroberts** [comment]
Hi! Yes, it does support the credentials and config files (it has for quite awhile), just not some of the advanced usage that has been added like the nested setting and stuff. If it's in a generic ini format, it'll be fine. This issue is just related to the expanded formatting that's now supported by aws.

You can also override paths used for credentials file and config file: https://github.com/miasma-rb/miasma-aws#profile-related-attributes

Cheers!

**Comment by dougireton** [comment]
Cool, thanks!

**Comment by chrisroberts** [comment]
Basic usage is in working order and includes source profile support
