### ISSUE TITLE
Support reading security/session tokens from credentials file

### ISSUE THREAD

**Issue by oifland** [miasma-rb/miasma-aws#30]
Right now, the keys "aws_session_token" / "aws_security_token" are what the awscli uses for the aws_sts_token. (See https://github.com/boto/botocore/blob/7dc06b0e554750b17ac3a3ca2af79734a3317b27/botocore/credentials.py#L461 )

Also, right now, quoted values don't lose the quotes when parsed. (Since session tokens can include '=' signs, some parsers require quotes around the values.)

I already coded these changes up, so I'll have a PR shortly.

**Comment by chrisroberts** [comment]
Release v0.2.4 has these fixes applied. Thanks for raising the issue and providing a PR!

Cheers!
