### ISSUE TITLE
don't bump version twice when releasing

### ISSUE THREAD

**Issue by grosser** [miasma-rb/miasma-aws#54]
![screen shot 2018-07-16 at 1 35 05 pm](https://user-images.githubusercontent.com/11367/42782217-12196f04-88fd-11e8-92cc-821ca8fb4479.png)

**Comment by pedrocarrico** [comment]
@grosser perhaps @chrisroberts adopted the odd-unstable/even-stable style releases just like linux did a while back ago? 🤔

**Comment by grosser** [comment]
the unstable never got released, so seems kinda odd

**Comment by chrisroberts** [comment]
Public releases have always been even, with odd versions being what's currently in development (and available in my private gem store). I've been looking at updating to using prerelease versions instead, but haven't updated things locally yet.

Cheers!
