### ISSUE TITLE
AWS: Credentials given to Api.new are completely overridden by those in aws credentials file

### ISSUE THREAD

**Issue by gtakechan** [miasma-rb/miasma-aws#57]
Hi Chris and all.

I have upgraded miasma-aws to 0.3.20 together with miasma, sfn and sparkleformation recently,
then I noticed that credentials in .sfn config are completely ignored even though I do not define the same parameter in the aws credentials file.

Credentials given to Api.new, `creds` are replaced by `new_creds` at l.452 of aws.rb, but `new_creds` seems to contain no information on `creds`.

**Comment by pedrocarrico** [comment]
I noticed this behaviour as well.

Here's the line in question:
https://github.com/miasma-rb/miasma-aws/blob/develop/lib/miasma/contrib/aws.rb#L452

This changed from `creds.replace(new_creds.merge(creds))` to `creds.replace(new_creds)` on https://github.com/miasma-rb/miasma-aws/commit/3ebd40e3e8664a5ced480aa16ff67a3d251f8801

Version 0.3.12 works great but version 0.3.14 starts exhibiting this behaviour.
Here's the complete changeset for comparison: https://github.com/miasma-rb/miasma-aws/compare/90612bf...177b8149d2535778b283d044ea1c8055d6afad77

I was trying to come up with a fix but I really don't know the exact details and motivation for all the code that lead to this change.

Can you please advise @chrisroberts , I'd be happy to pair with you on a solution for this issue.

**Comment by chrisroberts** [comment]
@gtakechan @pedrocarrico Thanks for reporting this issue! I've updated the testing structure around configuration loading to fully mimic instantiation behavior. The original isolated coverage was successful but was not a proper comprehensive result. Implementation updated to work within fixed tests and local usage tests with different configuration styles shows expected behaviors.

Cheers!
