### ISSUE TITLE
Feature: Instance profile support (Support for IAM roles?)

### ISSUE THREAD

**Issue by petecheslock** [miasma-rb/miasma-aws#6]
Hey @chrisroberts, is IAM role support available?  It didn't seem to be when reviewing the code, but wanted to check.

**Comment by chrisroberts** [comment]
It sure does! Relevant connection arguments: https://github.com/miasma-rb/miasma-aws#secure-token-service-related

**Comment by chrisroberts** [comment]
After a bit more discussion, this is in reference to instance profile support, which is not currently supported here. So lets make it supported.

**Comment by chrisroberts** [comment]
Released - v0.1.18
